name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Release
      run: |
        chmod +x Scripts/build_release.sh
        ./Scripts/build_release.sh
        
    - name: Create DMG
      run: |
        chmod +x Scripts/create_dmg.sh
        ./Scripts/create_dmg.sh
        
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: AudioKeeper-DMG
        path: "*.dmg"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: "*.dmg"
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Homebrew Formula
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Calculate SHA256 of the DMG file
        DMG_SHA256=$(curl -sL "https://github.com/${{ github.repository }}/releases/download/v${VERSION}/AudioKeeper-v${VERSION}.dmg" | shasum -a 256 | cut -d' ' -f1)
        
        # Update the formula file
        sed -i '' "s/version \"[^\"]*\"/version \"${VERSION}\"/" audiokeeper.rb
        sed -i '' "s/sha256 \"[^\"]*\"/sha256 \"${DMG_SHA256}\"/" audiokeeper.rb
        
        # Commit and push changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add audiokeeper.rb
        git diff --staged --quiet || git commit -m "chore: Auto-update Homebrew formula to v${VERSION}"
        git push