name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Release
      run: |
        chmod +x Scripts/build_release.sh
        ./Scripts/build_release.sh
        
    - name: Create DMG
      run: |
        chmod +x Scripts/create_dmg.sh
        ./Scripts/create_dmg.sh
        
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: AudioKeeper-DMG
        path: "*.dmg"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: "*.dmg"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}